section .text
[bits 32]

extern irq_common_stub

%macro IRQ_NOERRCODE 1
    global irq%1
    irq%1:
        cli
        push qword 0
        push qword %1
        jmp irq_common_stub
%endmacro

IRQ_NOERRCODE 32
IRQ_NOERRCODE 33
IRQ_NOERRCODE 34
IRQ_NOERRCODE 35
IRQ_NOERRCODE 36
IRQ_NOERRCODE 37
IRQ_NOERRCODE 38
IRQ_NOERRCODE 39
IRQ_NOERRCODE 40
IRQ_NOERRCODE 41
IRQ_NOERRCODE 42
IRQ_NOERRCODE 43
IRQ_NOERRCODE 44
IRQ_NOERRCODE 45
IRQ_NOERRCODE 46
IRQ_NOERRCODE 47
IRQ_NOERRCODE 48
IRQ_NOERRCODE 49
IRQ_NOERRCODE 50
IRQ_NOERRCODE 51
IRQ_NOERRCODE 52
IRQ_NOERRCODE 53
IRQ_NOERRCODE 54
IRQ_NOERRCODE 55
IRQ_NOERRCODE 56
IRQ_NOERRCODE 57
IRQ_NOERRCODE 58
IRQ_NOERRCODE 59
IRQ_NOERRCODE 60
IRQ_NOERRCODE 61
IRQ_NOERRCODE 62
IRQ_NOERRCODE 63
