section .text
bits 64

extern _isr_common_stub

%macro ISR_NOERRCODE 1
    global isr%1
    isr%1:
        cli
        push qword 0
        push qword %1
        jmp _isr_common_stub
%endmacro

%macro ISR_YESERRCODE 1
    global isr%1
    isr%1:
        cli
        push qword %1
        jmp _isr_common_stub
%endmacro

ISR_NOERRCODE 0
ISR_NOERRCODE 1
ISR_NOERRCODE 2
ISR_NOERRCODE 3
ISR_NOERRCODE 4
ISR_NOERRCODE 5
ISR_NOERRCODE 6
ISR_NOERRCODE 7
ISR_YESERRCODE 8
ISR_NOERRCODE 9
ISR_YESERRCODE 10
ISR_YESERRCODE 11
ISR_YESERRCODE 12
ISR_YESERRCODE 13
ISR_YESERRCODE 14
ISR_NOERRCODE 15
ISR_NOERRCODE 16
ISR_NOERRCODE 17
ISR_NOERRCODE 18
ISR_NOERRCODE 19
ISR_NOERRCODE 20
ISR_NOERRCODE 21
ISR_NOERRCODE 22
ISR_NOERRCODE 23
ISR_NOERRCODE 24
ISR_NOERRCODE 25
ISR_NOERRCODE 26
ISR_NOERRCODE 27
ISR_NOERRCODE 28
ISR_NOERRCODE 29
ISR_NOERRCODE 30
ISR_NOERRCODE 31

ISR_NOERRCODE 32
ISR_NOERRCODE 33
